### ISSUE TITLE
Unit Tests Fail

### ISSUE THREAD

**Issue by rjeike** [ianlee74/CSharp-Name-Parser#4]
All of the the unit test fail for me.

The first issue was that Assert.IsEquals doesn't actually call CompareTo on the Name object.  I implemented IEquatable<object> on the Name object and then change the call to:
Assert.IsTrue(result.Equals(expectedResult));

This fixed one of the three unit tests.  Unfortunately, it looks like the other two simply don't Parse correctly.  At this point, I realized the library probably doesn't really work, so I abandoned it.  Let me know if this is an active project, it would be good to have a good C# name parser available.

Cheers,

-Randall

**Comment by ianlee74** [comment]
@rjeike - Sorry but this project never went very far before I abandoned it. I now use a SQL based solution since its more efficient for my needs. However, this is a very hard problem and one I'm continually improving. A C# function that works would indeed be handy. I don't think a function that works 100% of the time is possible especially if you have to deal with Latin/Mexican names but you can get it working for a majority of names. Feel free to fork and continue improving where I left off.

Ian
